name: PyPI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish-python-package:
    name: PyPI upload
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: pypi_package

      - name: Display structure of downloaded files
        run: ls -R
