name: PyPI

on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  publish-python-package:
    name: PyPI upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: PyPI package
          path: klayout_package/python/dist/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: klayout_package/python/dist/
